require: rubocop-rspec

LineLength:
  Max: 100

AbcSize:
  Max: 20

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

WordArray:
  Enabled: false

SymbolArray:
  Enabled: false

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/requests/**/*_spec.rb'

Style/MutableConstant:
  Enabled: false

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Rails/SkipsModelValidations:
  Whitelist:
    - increment_counter
    - decrement_counter

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/**/*.rb'
